name: Build KKBridge Plugin

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: src/KKBridge.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: "17.0"

      - name: Build the solution
        run: |
          msbuild /m /nr:false /p:UseSharedCompilation=false /p:Configuration=${{ env.BUILD_CONFIGURATION }} ${{ env.SOLUTION_FILE_PATH }}

      - name: Prepare package for upload
        shell: bash
        run: |
          RELEASE_DIR="src/bin/${{ env.BUILD_CONFIGURATION }}"
          PACKAGE_DIR="BepInEx/plugins/KKBridge"
          mkdir -p "$PACKAGE_DIR/out"
          cp -r src/DLLs "$PACKAGE_DIR/"
          cp "src/Config/config.json" "$PACKAGE_DIR/"
          cp "$RELEASE_DIR/KKBridge.dll" "$PACKAGE_DIR/"

          echo "Final structure:"
          find "$PACKAGE_DIR" -print

          7z a -t7z KKBridge.7z BepInEx/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KKBridge_Build_${{ github.run_number }}
          path: KKBridge.7z
